Changes necessary to make at least download from fanfiction.net possible.
Still crashes in the end (while creating working EPub)

$ fanficfare https://www.fanfiction.net/s/12029238
......Traceback (most recent call last):
  File "/home/matej/.local/bin/fanficfare", line 11, in <module>
    load_entry_point('FanFicFare', 'console_scripts', 'fanficfare')()
  File "/home/matej/archiv/knihovna/repos/FanFicFare/fanficfare/cli.py", line 263, in main
    passed_personalini)
  File "/home/matej/archiv/knihovna/repos/FanFicFare/fanficfare/cli.py", line 444, in do_download
    output_filename = write_story(configuration, adapter, options.format, options.metaonly)
  File "/home/matej/archiv/knihovna/repos/FanFicFare/fanficfare/cli.py", line 61, in write_story
    writer.writeStory(outstream=outstream, metaonly=metaonly)
  File "/home/matej/archiv/knihovna/repos/FanFicFare/fanficfare/writers/base_writer.py", line 229, in writeStory
    self.writeStoryImpl(outstream)
  File "/home/matej/archiv/knihovna/repos/FanFicFare/fanficfare/writers/writer_epub.py", line 581, in writeStoryImpl
    '<meta name="cover" content="%s"/>' % coverimgid)
TypeError: a bytes-like object is required, not 'str'
$